# Generated by Django 3.1.7 on 2021-03-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Q2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='bin',
            field=models.ManyToManyField(blank=True, to='Q2.Bin'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='operation',
            field=models.ManyToManyField(blank=True, to='Q2.Operation'),
        ),
    ]
