# Generated by Django 3.1.7 on 2021-03-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Q2', '0003_auto_20210315_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='bin',
        ),
        migrations.AddField(
            model_name='collection',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Q2.bin'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='operation',
        ),
        migrations.AddField(
            model_name='collection',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Q2.operation'),
        ),
    ]
