# Generated by Django 3.1.7 on 2021-03-15 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Q2', '0004_auto_20210315_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q2.bin'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Q2.operation'),
        ),
    ]
